exclude: (tests|migrations|frontend|venv|env)/.*
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
    - id: seed-isort-config
      args: ["--application-directories=api,recipes,users"]

- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
    - id: isort

- repo: local

  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [
        "--ignore=W503,R505",
        "--max-line-length=79",
        "--per-file-ignores=*/settings.py:E501"
      ]
